---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
  labels:
    app: oauth2-proxy    
data:
  oauth2-proxy.cfg: |
    https_address = "0.0.0.0:4443"
    metrics_address = "0.0.0.0:9100"    
    tls_cert_file = "/etc/oauth2-proxy/certs/tls.crt"
    tls_key_file =  "/etc/oauth2-proxy/certs/tls.key"
    redirect_url = "https://oauth2-proxy.labo.local:4443/oauth2/callback"
    provider = "oidc"
    provider_display_name = "My OIDC Provider"
    oidc_issuer_url = "https://dex.labo.local:32000/"
    insecure_oidc_skip_issuer_verification = true
    email_domains = [
        "*"
    ]
    whitelist_domains = [
        "ingress.k8s1.labo.local"
    ]

    ssl_insecure_skip_verify = true
    cookie_name = "_oauth2_proxy"
    cookie_secure = true
    cookie_domains = ".labo.local"
    cookie_expire = "1m"
    cookie_refresh = "30s"
    cookie_httponly = true
