apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
  labels:
    app: oauth2-proxy
type: Opaque
stringData:
  client-id: oauth2-proxy
  client-secret: 6af3c2359973e42a5e95e28c2e97646c775936e1
  cookie-secret: ZGRLMXFNTi9wSTNmdjE2bHNldFNhZz09



