apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
  labels:
    app: oauth2-proxy    
spec:
  type: LoadBalancer
  ports:
    - name: https  
      port: 4443
      targetPort: 4443
      protocol: TCP

    - port: 9100
      protocol: TCP
      targetPort: metrics
      name: metrics
  selector:
    app: oauth2-proxy  

