apiVersion: v1
kind: Secret
metadata:
  name: github-client
  namespace: dex  
type: Opaque
stringData:
  client-id: "f0b88fbfc24a0b4e9395"
  client-secret: "8fd4056adbfdd032f5ad605f2f8a7c34a26abf69"
